apiVersion: v1
kind: Service
metadata:
  name: rollem-ui-lb
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "rollem.rocks"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "e0d8f72f-da50-4e06-89c2-d2e54dc081f4"
    service.beta.kubernetes.io/do-loadbalancer-hostname: "rollem.rocks"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: https
      port: 443
      targetPort: 3000
  selector:
    app: rollem-ui