nmHoistingLimits: workspaces

# publish config
npmPublishRegistry: https://registry.npmjs.org/
npmPublishAccess: public
changesetBaseRefs:
  - v2.10.2
changesetIgnorePatterns:
  - "**/*.spec.{js,ts}"

plugins:
  - checksum: 5e73a1acbb9741fce1e8335e243c9480ea2107b9b4b65ed7643785ddea9e3019aee254a92a853b1cd71023b16fff5b7d3afd5256fe57cd35a54f8785b8c30281
    path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://go.mskelton.dev/yarn-outdated/v4"
  - checksum: cd3f4b29fc21d0ba90e019d9ab5676869b6e573c1c390d9037c1f1f5e367026f341d5b07c5aa2c408d4db56b03eb65efa3e94aa49a01d4ba7ebfba829697fef3
    path: .yarn/plugins/@yarnpkg/plugin-interractive-filter.cjs
    spec: "https://raw.githubusercontent.com/eyolas/yarn-plugin-interractive-filter/master/bundles/%40yarnpkg/plugin-interractive-filter.js"
