services:
  # Database is required for persistence
  database:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./resources/database/.storage/data:/var/lib/postgresql/data
    env_file:
      - ./secrets/docker.env

  # Rollem UI
  rollem-ui:
    image: rollem/ui
    ports:
      - "9000:9000"
      - "3000:3000"
    depends_on:
      - database
    env_file:
      - ./secrets/docker.env # Requires configuration for (local) login to work

  # Rollem Discord Bot
  rollem-discord:
    image: rollem/discord
    depends_on:
      - database
    env_file:
      - ./secrets/docker.env # Requires configuration for to work

