services:
  grafana-alloy:
    image: grafana/alloy:latest
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    ports:
      - "12345:12345"
    volumes:
      - ./config/config.alloy:/etc/alloy/config.alloy
    env_file:
      - ../../secrets/docker.env