apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollem-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rollem-ui
  template:
    metadata:
      labels:
        app: rollem-ui
    spec:
      nodeSelector:
        doks.digitalocean.com/node-pool: pool-rollem
      containers:
      - name: rollem-ui
        image: lemtzas/rollem-discord-ui:2.10.1
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          requests:
            cpu: 150m
            memory: 200M
        env:
        - name: 'reboot'
          value: '2021-10-28'
        - name: 'DISCORD_CLIENT_ID'
          valueFrom:
            secretKeyRef:
              name: rollem-ui
              key: DISCORD_CLIENT_ID
        - name: 'DISCORD_CLIENT_SECRET'
          valueFrom:
            secretKeyRef:
              name: rollem-ui
              key: DISCORD_CLIENT_SECRET
        - name: 'DISCORD_REDIRECT_URI'
          valueFrom:
            secretKeyRef:
              name: rollem-ui
              key: DISCORD_REDIRECT_URI
        - name: 'DB_CONNECTION_STRING'
          valueFrom:
            secretKeyRef:
              name: rollem-ui
              key: DB_CONNECTION_STRING