name: Docker Build

on:
  workflow_call:

jobs:
  build-image--rollem-ui:
    runs-on: ubuntu-latest
    name: Containerize (Rollem UI)

    steps:
    - uses: actions/checkout@v2

    - name: Build Image (UI)
      working-directory: .
      run: docker build -f workspace.Dockerfile . --target rollem-ui --label='rollem-ui' -t rollem-ui

    - name: Export Image (UI)
      working-directory: .
      run: docker save rollem-ui > /tmp/rollem-ui.tar

    - name: Archive Images
      uses: actions/upload-artifact@v4
      with:
        name: rollem-ui
        path: /tmp/rollem-ui.tar