{
 "title": "Rollem Prod",
 "tags": [ "rollem" ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Popularity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Servers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(max_over_time(rollem_servers{job=\"rollem-next-transitional/rollem-next\"}[5m]))",
     "legendFormat": "rollem-next"
    },
    {
     "expr": "sum(max_over_time(rollem_servers{job=\"rollem-prod-transitional/rollem-prod\"}[5m]))",
     "legendFormat": "rollem-prod"
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(max_over_time(rollem_users{job=\"rollem-next-transitional/rollem-next\"}[5m]))",
     "legendFormat": "rollem-next"
    },
    {
     "expr": "sum(max_over_time(rollem_users{job=\"rollem-prod-transitional/rollem-prod\"}[5m]))",
     "legendFormat": "rollem-prod"
    }
   ]
  },
  {
   "title": "Servers per Shard",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "max by(shard) (rollem_servers{job=\"rollem-prod-transitional/rollem-prod\"})",
     "legendFormat": "prod-{{shard}}"
    },
    {
     "expr": "max by(shard) (rollem_servers{job=\"rollem-next-transitional/rollem-next\"})",
     "legendFormat": "next-{{shard}}"
    }
   ]
  },
  {
   "title": "Prod Uptime",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "min by(shard) ((time() - process_start_time_seconds{job=\"rollem-prod-transitional/rollem-prod\"}) / 60)",
     "legendFormat": "prod-{{shard}}"
    },
    {
     "expr": "min by(shard) ((time() - process_start_time_seconds{job=\"rollem-next-transitional/rollem-next\"}) / 60)",
     "legendFormat": "next-{{shard}}"
    }
   ]
  },
  { "title": "Handled Events [5m]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Handler Uses (Prod)",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "label_replace(label_join(sum by(handler_type, handler_subtype) (increase(rollem_handlers_used{job=\"rollem-prod-transitional/rollem-prod\"}[5m])), \"handler\", \"/\", \"handler_type\", \"handler_subtype\"), \"handler\", \"$1\", \"handler\", \"(.*?)/undefined\")",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Handler Uses (Next)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "label_replace(label_join(sum by(handler_type, handler_subtype) (increase(rollem_handlers_used{job=\"default/rollem-next\"}[5m])), \"handler\", \"/\", \"handler_type\", \"handler_subtype\"), \"handler\", \"$1\", \"handler\", \"(.*?)/undefined\")",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Handled Events",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by(shard) (increase(rollem_events_processed{job=\"rollem-prod-transitional/rollem-prod\"}[5m]))",
     "legendFormat": "prod-{{shard}}"
    },
    {
     "expr": "sum by(shard) (increase(rollem_events_processed{job=\"rollem-next-transitional/rollem-next\"}[5m]))",
     "legendFormat": "next-{{shard}}"
    },
    {
     "expr": "sum by(shard) (increase(rollem_events_processed{job=\"default/rollem-next\"}[5m]))",
     "legendFormat": "next-{{shard}}"
    }
   ]
  },
  {
   "title": "Handled Events",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by(shard) (increase(rollem_events_processed{job=\"rollem-prod-transitional/rollem-prod\"}[5m]))",
     "legendFormat": "prod-{{shard}}"
    },
    {
     "expr": "sum by(shard) (increase(rollem_events_processed{job=\"rollem-next-transitional/rollem-next\"}[5m]))",
     "legendFormat": "next-{{shard}}"
    },
    {
     "expr": "sum by(shard) (increase(rollem_events_processed{job=\"default/rollem-next\"}[5m]))",
     "legendFormat": "next-{{shard}}"
    }
   ]
  },
  {
   "title": "Handled Events",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(shard) (increase(rollem_events_processed{job=\"rollem-next-transitional/rollem-next\"}[5m]))",
     "legendFormat": "next-{{shard}}"
    },
    {
     "expr": "sum by(shard) (increase(rollem_events_processed{job=\"default/rollem-next\"}[5m]))",
     "legendFormat": "next-{{shard}}"
    }
   ]
  },
  {
   "title": "Handled Events",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(shard) (increase(rollem_events_processed{job=\"rollem-prod-transitional/rollem-prod\"}[5m]))",
     "legendFormat": "prod-{{shard}}"
    }
   ]
  }
 ]
}