{
 "title": "Rollem Prod",
 "tags": [ "rollem" ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Popularity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Servers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(max_over_time(rollem_servers{job=\"default/rollem-next\"}[5m]))",
     "legendFormat": "rollem-next"
    },
    {
     "expr": "sum(max_over_time(rollem_servers{job=\"default/rollem-prod\"}[5m]))",
     "legendFormat": "rollem-prod"
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(max_over_time(rollem_users{job=\"default/rollem-next\"}[5m]))",
     "legendFormat": "rollem-next"
    },
    {
     "expr": "sum(max_over_time(rollem_users{job=\"default/rollem-prod\"}[5m]))",
     "legendFormat": "rollem-prod"
    }
   ]
  },
  { "title": "Servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Servers per Shard (Next)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "max by(shard) (rollem_servers{job=\"default/rollem-next\"})",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Servers per Shard (Prod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "max by(shard) (rollem_servers{job=\"default/rollem-prod\"})",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  { "title": "Handled Events [5m]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Rolls (Prod)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by(handler_subtype) (increase(rollem_handlers_used{job=\"default/rollem-prod\", handler_type=\"roll\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rolls (Next)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 19 },
   "targets": [
    {
     "expr": "sum by(handler_subtype) (increase(rollem_handlers_used{job=\"default/rollem-next\", handler_type=\"roll\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Handled Events (Prod)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum by(shard) (increase(rollem_events_processed{job=\"default/rollem-prod\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Handler Uses (Prod)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by(handler_type) (increase(rollem_handlers_used{job=\"default/rollem-prod\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Handler Uses (Next)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 29 },
   "targets": [
    {
     "expr": "sum by(handler_type) (increase(rollem_handlers_used{job=\"default/rollem-next\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Handled Events (Next)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum by(shard) (increase(rollem_events_processed{job=\"default/rollem-next\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Uptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Prod Uptime",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "min by(shard) ((time() - process_start_time_seconds{job=\"default/rollem-prod\"}) / 60)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Next Uptime",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "min by(shard) ((time() - process_start_time_seconds{job=\"default/rollem-next\"}) / 60)\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}