apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollem-next-t-00-deployment
  namespace: rollem-next-transitional
spec:
  selector:
    matchLabels:
      app: rollem-next-t
  replicas: 1
  template:
    metadata:
      labels:
        app: rollem-next-t
    spec:
      nodeSelector:
        doks.digitalocean.com/node-pool: pool-rollem
      containers:
      - name: rollem-next-t-00
        image: rollem/discord:date-2025.02.18-06.26--pr-236--sha-cd926f5
        imagePullPolicy: IfNotPresent
        ports:
        - name: web
          containerPort: 8081
        resources:
          requests:
            cpu: 75m
            memory: 300M
        env:
        - name: 'reboot'
          value: '2023-10-09.2'
        - name: DISCORD_BOT_SHARDSET_ID
          value: '0'
        - name: DISCORD_BOT_SHARDSET_COUNT
          value: '1'
        - name: DISCORD_BOT_SHARDSET_SHARDS_PER_SET
          value: '8'
        - name: ROLLEM_LOCAL_DIAGNOSTIC_MODE
          value: 'true'
        - name: OPENTELEMETRY_ATTR_SERVICE_NAME
          value: 'next.discord.rollem.rocks'
        - name: OPENTELEMETRY_ATTR_SERVICE_VERSION
          value: 'rollem-next-t'

        - name: 'DISCORD_BOT_USER_TOKEN'
          valueFrom:
            secretKeyRef:
              name: rollem-next
              key: DISCORD_BOT_USER_TOKEN
        - name: 'APPINSIGHTS_CONNECTIONSTRING'
          valueFrom:
            secretKeyRef:
              name: rollem-next
              key: APPINSIGHTS_CONNECTIONSTRING
        - name: 'DEFER_TO_CLIENT_IDS'
          valueFrom:
            secretKeyRef:
              name: rollem-next
              key: DEFER_TO_CLIENT_IDS
        - name: 'DB_CONNECTION_STRING'
          valueFrom:
            secretKeyRef:
              name: rollem-next
              key: DB_CONNECTION_STRING