name: Docker Publish (UI)

on:
  workflow_call:
    inputs:
      tagging_method:
        description: 'pr | commit | version-tag'
        required: true
        type: string
    secrets:
      DOCKER_HUB_USER:
        description: 'asdf'
        required: true
      DOCKER_HUB_TOKEN:
        required: true

env:
  IMAGE_NAME: ${{ env.IMAGE_NAME }}

jobs:
  push-image-rollem-ui:
    runs-on: ubuntu-latest
    name: Publish (Rollem UI)

    steps:
      - name: Validate tagging method
        if: contains(fromJson('["pr", "commit", "version-tag"]'), github.event.action)
        run: exit 1 # fails the job

      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Metadata - Tag as Version
        if: inputs.tagging_method == 'version-tag'
        id: meta-version
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ vars.DOCKER_HUB_USER }}/${{ env.IMAGE_NAME}}
            ghcr.io/rollem-discord/${{ env.IMAGE_NAME}}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          flavor: |
            latest=auto

      - name: Metadata - Tag as PR
        if: inputs.tagging_method == 'pr'
        id: meta-pr
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ vars.DOCKER_HUB_USER }}/${{ env.IMAGE_NAME}}
            ghcr.io/rollem-discord/${{ env.IMAGE_NAME}}
          tags: |
            type=ref,event=pr
            type=raw,value=date-{{date 'YYYY.MM.DD-HH.mm'}}--pr-${{ github.event.number }}--sha-{{sha}}
          flavor: |
            latest=false

      - name: Metadata - Tag as Commit
        if: inputs.tagging_method == 'commit'
        id: meta-commit
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ vars.DOCKER_HUB_USER }}/${{ env.IMAGE_NAME}}
            ghcr.io/rollem-discord/${{ env.IMAGE_NAME}}
          tags: |
            type=ref,event=branch
            type=raw,value=date-{{date 'YYYY.MM.DD-HH.mm'}}--{{branch}}--sha-{{sha}}
          flavor: |
            latest=false

      # - name: Build and push
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     file: workspace.Dockerfile
      #     target: rollem-ui
      #     push: ${{ github.event_name != 'pull_request' }}
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}

      # - name: Generate artifact attestation
      #   uses: actions/attest-build-provenance@v1
      #   with:
      #     subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
      #     subject-digest: ${{ steps.push.outputs.digest }}
      #     push-to-registry: true