name: Docker Build (UI)

on:
  workflow_call:

jobs:
  build-image--rollem-ui:
    runs-on: ubuntu-latest
    name: Build (UI)

    steps:
    - uses: actions/checkout@v2

    - name: Build Image
      working-directory: .
      run: docker build -f workspace.Dockerfile . --target rollem-ui --label='rollem-ui' -t rollem-ui

    - name: Export Image
      working-directory: .
      run: docker save rollem-ui > /tmp/rollem-ui.tar

    - name: Archive
      uses: actions/upload-artifact@v4
      with:
        name: rollem-ui
        path: /tmp/rollem-ui.tar