name: Docker (PR)

on:
  pull_request:
    branches: [ main ]

jobs:
  # These only produce artifacts -- they are always run
  # build-image--rollem-ui:
  #   uses: ./.github/workflows/--docker-build--rollem-ui.yml
  # build-image--rollem-discord:
  #   uses: ./.github/workflows/--docker-build--rollem-discord.yml
  # build-image--rollem-mastodon:
  #   uses: ./.github/workflows/--docker-build--rollem-mastodon.yml

  # These only produce artifacts -- they are only run 
  build-push-image--rollem-ui:
    uses: ./.github/workflows/--docker-build-publish--rollem-ui.yml
    secrets: inherit
    with:
      tagging_method: pr
  # build-push-image--rollem-discord:
  #   uses: ./.github/workflows/--docker-build--rollem-discord.yml
  # build-push-image--rollem-mastodon:
  #   uses: ./.github/workflows/--docker-build--rollem-mastodon.yml