name: Docker (PR)

on:
  pull_request:
    branches: [ main ]

jobs:
  # These only produce artifacts
  # build-image--rollem-ui:
  #   uses: ./.github/workflows/--docker-build--rollem-ui.yml
  # build-image--rollem-discord:
  #   uses: ./.github/workflows/--docker-build--rollem-discord.yml
  # build-image--rollem-mastodon:
  #   uses: ./.github/workflows/--docker-build--rollem-mastodon.yml

  job:
    runs-on: ubuntu-latest
    name: Check values
    steps:
      - name: Check Values
        run: echo "github.actor = '${{ github.actor }}'"
  # build-push-image--rollem-ui:
  #   uses: ./.github/workflows/--docker-build-publish--common.yml
  #   secrets: inherit
  #   with:
  #     IMAGE_NAME: ui
  #     BUILD_TARGET_STAGE: rollem-ui
  #     tagging_method: pr

  # build-push-image--rollem-discord:
  #   needs: build-push-image--rollem-ui # these are chained to reduce total-build-minutes by way of cache; remove for shorter overall build duration
  #   uses: ./.github/workflows/--docker-build-publish--common.yml
  #   secrets: inherit
  #   with:
  #     IMAGE_NAME: discord
  #     BUILD_TARGET_STAGE: rollem-discord
  #     tagging_method: pr

  # build-push-image--rollem-mastodon:
  #   needs: build-push-image--rollem-discord # these are chained to reduce total-build-minutes by way of cache; remove for shorter overall build duration
  #   uses: ./.github/workflows/--docker-build-publish--common.yml
  #   secrets: inherit
  #   with:
  #     IMAGE_NAME: mastodon
  #     BUILD_TARGET_STAGE: rollem-mastodon
  #     tagging_method: pr